In [1]:
import sys, os
from typing import Optional
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: c:\Users\User\Desktop\NYU stuff\Jay's financial modelling\FRE-GT-9743-Assignment-4
Fixed Income Library is loaded.

# Instructions for HW4:

## Product Display

This time we will display the products that you built before.
Based on your knowledge, please decide what to display.

The changes will be made to product_display_visitor.py

1. Bullet Cashflow

In [2]:
# Product Bullet Cashflow

termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
long_or_short = 'LONG'
payment_date = qfAddPeriod(termination_date, '2D', 'F', 'USGS')

# qfCreateProductBulletCashflow is one of api, check lower-level class 'ProductBulletCashflow' for implementation

prod_bullet_cashflow = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short,
    payment_date
)

In [3]:
qfDisplayProduct(prod_bullet_cashflow)

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long or Short                     LONG
4  Termination Date               2026-05-26
5      Payment Date               2026-05-28

In [4]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
accrual_basis = 'ACT/360'
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)

prod_fixed_accrued = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    currency,
    notional,
    accrual_basis,
    payment_date,
    business_day_convention, 
    holiday_convention
)

In [5]:
qfDisplayProduct(prod_fixed_accrued)

               Name                  Value
0      Product Type  PRODUCT_FIXED_ACCRUED
1          Notional              1000000.0
2          Currency                    USD
3     Long or Short                   LONG
4    Effective Date             2026-03-26
5  Termination Date             2026-05-26
6     Accrual Basis                ACT/360
7           Accrued               0.169444

3. Overnight Index Cashflow

In [6]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2027-03-26'
term = '1Y'
overnight_index = 'SOFR-1B'
notional = 1e6
compounding_method = 'compound'
spread = 0.005
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)

product_on_cashflow = qfCreateProductOvernightIndexCashflow(
    effecitve_date,
    term,
    overnight_index,
    notional,
    compounding_method,
    spread,
    payment_date)

In [7]:
qfDisplayProduct(product_on_cashflow)

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-29
6        Payment Date                        2027-03-30
7     Overnight Index                 SOFRON Actual/360
8  Compounding Method                          COMPOUND
9              Spread                             0.005

4. RFR Swap

In [8]:
effective_date = '2025-05-25'
termination_date = '2027-05-25'
term = '2Y'
pay_offset = '2D'
on_index = 'SOFR-1B'
fixed_rate = 0.04
pay_or_rec = 'pay'
notional = 1e6
accrual_peroid = '1Y'
accrual_basis = 'ACT/360'
floating_leg_accrual_period = '1Y'
business_day_convention = 'F'
holiday_convention = 'USGS'
spread = 0.005
compounding_method = 'compound'

product_on_rfr_swap = qfCreateProductRFRSwap(
    effective_date,
    term,
    pay_offset,
    on_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_peroid,
    accrual_basis,
    floating_leg_accrual_period,
    business_day_convention,
    holiday_convention,
    spread,
    compounding_method)

In [9]:
qfDisplayProduct(product_on_rfr_swap)

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional          1000000.0
2                      Currency                USD
3                 Long or Short               LONG
4                Effective Date         2025-05-25
5              Termination Date         2027-05-25
6                Payment Offset                 2D
7               Overnight Index  SOFRON Actual/360
8            Compounding Method           COMPOUND
9                        Spread              0.005
10                   Fixed Rate               0.04
11               Pay or Receive                PAY
12                Accrual Basis            ACT/360
13     Fixed Leg Accrual Period                 1Y
14  Floating Leg Accrual Period                 1Y
15      Business Day Convention                  F
16           Holiday Convention               USGS